version: "3.4"

# LoginID Demo
#
# The default compose file for the tutorial
# To debug java code use 'docker-compose-dev.yml'
#
services:

  # contains the website and backend (UserMgmt)
  # this container is enabled for remote debugging on port 8000
  #
  usermgmt:
    container_name: tutorial_backend
    image: local/tutorial_backend:latest
    restart: always
    ports:
      - "80:${PORT_SERVICE}"
      - "8000:8000"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"
      - "BACKENDCLIENTID=${CLIENT_ID_BACKEND}"
      - "APIPRIVATEKEY=${API_PRIVATE_KEY}"
      - "KONGLOCATION=${KONG_LOCATION}"
      - "PORT=${PORT_SERVICE}"
      - "OIDC_PUBLIC_CLIENT_ID=${OIDC_PUBLIC_CLIENT_ID}"
      - "OIDC_REDIRECT_PUBLIC_CLIENT=${OIDC_REDIRECT_PUBLIC_CLIENT}"
      - "OIDC_SCOPE=${OIDC_SCOPE}"
      - "OIDC_CONFIG_ENDPOINT=${OIDC_CONFIG_ENDPOINT}"

  # contains the kong docker gateway including the LoginID plugin
  #
  kong:
    container_name: tutorial_kong_gw
    image: local/tutorial_kong_gw:latest
    restart: always
    ports:
      - "8090:${PORT_KONG}"
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"
      - "PORT=${PORT_KONG}"