version: "3.4"

# LoginID Demo
#
# The default compose file for the demo
# To debug java code or do 'live' changes in the web UI use 'docker-compose-dev.yml'
#
services:

  # contains the website
  # changes in ./web will be displayed in the UI after a refresh (most of the times)
  #
  nginx:
    container_name: demo_app
    image: local/kongclient
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"

  # contains the backend (UserMgmt)
  # this container is enabled for remote debugging on port 8000
  #
  usermgmt:
    container_name: user_mgmt_api
    image: local/usermgmt
    restart: always
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - .env:/opt/docker/loginid/config

  # contains the kong docker gateway including the LoginID plugin
  #
  kong:
    container_name: api_gateway
    image: local/kong
    restart: always
    ports:
      - "8090:8000"
      - "8001:8001"
      - "8444:8444"
    environment:
      - "KONG_DATABASE=off"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"