version: "3.4"

# LoginID Demo
#
# The compose file will pull pre-built images from Docker Hub (hub.docker.com)
#
# To use this follow the instructions to create an .env file. Once the .env file is available,
# use this file by running: docker-compose -f docker-compose-hub.yml up'
#
services:

  # contains the website and backend (UserMgmt)
  #
  usermgmt:
    container_name: tutorial_backend
    image: saschaloginid/tutorial_backend:latest
    restart: always
    ports:
      - "80:${PORT_SERVICE}"
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"
      - "BACKENDCLIENTID=${CLIENT_ID_BACKEND}"
      - "APIPRIVATEKEY=${API_PRIVATE_KEY}"
      - "KONGLOCATION=${KONG_LOCATION}"
      - "PORT=${PORT_SERVICE}"
      - "OIDC_PUBLIC_CLIENT_ID=${OIDC_PUBLIC_CLIENT_ID}"
      - "OIDC_REDIRECT_PUBLIC_CLIENT=${OIDC_REDIRECT_PUBLIC_CLIENT}"
      - "OIDC_SCOPE=${OIDC_SCOPE}"
      - "OIDC_CONFIG_ENDPOINT=${OIDC_CONFIG_ENDPOINT}"

  # contains the kong docker gateway including the LoginID plugin
  #
  kong:
    container_name: tutorial_kong_gw
    image: saschaloginid/tutorial_kong_gw:latest
    restart: always
    ports:
      - "8090:${PORT_KONG}"
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"
      - "PORT=${PORT_KONG}"