version: "3.4"

services:

  nginx:
    container_name: demo_app
    image: local/kongclient
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro

  ui:
    container_name: demo_ui
    image: local/ui
    restart: always
    ports:
      - '3000:3000'
    command:
      "npm start"

  kong:
    container_name: api_gateway
    image: local/kong
    restart: always
    ports:
      - "8090:8000"
      - "8001:8001"
      - "8444:8444"
    environment:
      - "KONG_DATABASE=off"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"

  usermgmt:
    container_name: user_mgmt_api
    image: local/usermgmt
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "BASE_URL=https://directweb.usw1.loginid.io"