version: "3.4"

services:

  nginx:
    image: local/kongclient
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro

  kong:
    image: local/kong
    container_name: kong
    restart: always
    ports:
      - "8090:8000"
      - "8001:8001"
      - "8444:8444"
    environment:
      - "KONG_DATABASE=off"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"