#
# This image runs the local docker based Kong gateway (no database)
#
FROM kong
COPY docker-build/add-ons/kong/kong.conf /etc/kong/kong.conf
COPY docker-build/add-ons/kong/kong.yml /etc/kong/kong.yml
COPY docker-build/add-ons/kong/plugins/kong-loginid-plugin-20211103/kong-plugin-loginid-0.1.0-1.rockspec /usr/local/lib/luarocks/rocks-5.1/kong-plugin-loginid/0.1.0-1/kong-plugin-loginid-0.1.0-1.rockspec
COPY docker-build/add-ons/kong/plugins/kong-loginid-plugin-20211103/kong/plugins/loginid/ /usr/local/share/lua/5.1/kong/plugins/loginid

# Using root so that the entrypoint script can update variables (convenience)
#
USER root
COPY docker-build/add-ons/kong/docker-entrypoint.sh /docker-entrypoint.sh
