version: "3.4"

# LoginID Demo
#
# The default compose file for the demo
# To debug java code use 'docker-compose-dev.yml'
#
services:

  # contains the website and backend (UserMgmt)
  #
  usermgmt:
    container_name: tutorial_backend
    image: local/tutorial_backend:latest
    restart: always
    ports:
      - "80:8080"
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"
      - "BACKENDCLIENTID=${CLIENT_ID_BACKEND}"
      - "APIPRIVATEKEY=${API_PRIVATE_KEY}"
#    volumes:
#      - .env:/opt/docker/loginid/config

  # contains the kong docker gateway including the LoginID plugin
  #
  kong:
    container_name: tutorial_kong_gw
    image: local/tutorial_kong_gw:latest
    restart: always
    ports:
      - "8090:8000"
    environment:
      - "KONG_DATABASE=off"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "HOSTNAME=${HOSTNAME}"
      - "BASEURL=${BASE_URL}"
      - "WEBCLIENTID=${CLIENT_ID_WEB}"